# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('scpstp', ['core'])
    module.source = [
        'model/scpstp.cc',
        'helper/scpstp-helper.cc',
        'model/scpstp-socket-factory.cc',
        'model/scpstp-socket-factory-impl.cc',
        'model/scpstp-l4-protocol.cc',
        'model/scpstp-socket-base.cc',
        ]

    module_test = bld.create_ns3_module_test_library('scpstp')
    module_test.source = [
        'test/scpstp-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/scpstp-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'scpstp'
    headers.source = [
        'model/scpstp.h',
        'helper/scpstp-helper.h',
        'model/scpstp-socket-factory.h',
        'model/scpstp-socket-factory-impl.h',
        'model/scpstp-l4-protocol.h',
        'model/scpstp-socket-base.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()

